name: video_snapshot_generator
description: Generate video thumbnails with custom dimensions and quality settings for Flutter applications.
version: 0.1.0
homepage: https://github.com/Dhia-Bechattaoui/video_snapshot_generator
repository: https://github.com/Dhia-Bechattaoui/video_snapshot_generator
issue_tracker: https://github.com/Dhia-Bechattaoui/video_snapshot_generator/issues
documentation: https://github.com/Dhia-Bechattaoui/video_snapshot_generator#readme

keywords:
  - android
  - cross-platform
  - flutter
  - ios
  - linux
  - macos
  - media
  - snapshot
  - utilities
  - video
  - web
  - windows

topics:
  - images
  - media
  - utilities
  - thumbnail
  - video-processing

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.32.0"

funding:
  - https://github.com/sponsors/Dhia-Bechattaoui

dependencies:
  cross_platform_video_thumbnails: ^0.1.1
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.0.0
  coverage: ^1.0.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  test: ^1.0.0

flutter:
  # No Flutter-specific dependencies needed for this package
